Repository GSG-FC03/Covid-19-app, pull requests merged in 2021-08, with the labels that each got.

#37 create-file-structure
  advice/advice.css
  advice/advice.html
  advice/advice.js
  contact/contact.css
  contact/contact.html
  contact/contact.js
  covid-vaccine-tracker/covid-vaccine-tracker.css
  covid-vaccine-tracker/covid-vaccine-tracker.html
  covid-vaccine-tracker/covid-vaccine-tracker.js
  home/home.css
  home/home.html
  home/home.js
  index.html
  main.js
  style.css
  symptoms/symptoms.css
  symptoms/symptoms.html
  symptoms/symptoms.js
Labels: waiting-review

#40 create index page
  assets/home.svg
  index.html
  style.css
Labels: in-progress

#45 Fix the index.html page
  index.html
Labels: Approve

#41 create contact html
  assets/Ellipse 113.png
  assets/Vector.png
  assets/coviddd.png
  assets/dark-mode.png
  contact/contact.html
Labels: waiting-review

#42 create contact css
  contact/contact.css
  contact/contact.html
Labels: waiting-review

#48 add an image instead of the letter o
  index.html
  style.css
Labels: waiting-review

#47 create symptoms css, js file
  assets/sun.svg
  symptoms/symptoms.css
  symptoms/symptoms.html
  symptoms/symptoms.js
Labels: waiting-review

#50 Creat advice css
  advice/advice.css
  advice/advice.html
  advice/advice.js
Labels: done

#55 Making the style responsive for iPad pro
  symptoms/symptoms.css
Labels: waiting-review

#51 create index page
  advice/advice.html
  index.html
  main.js
  style.css
Labels: waiting-review

#54 add read me file
  README.md
  assets/Covid Vaccine Tracker – 1.png
  assets/Covid Vaccine Tracker.png
  assets/Symptoms page.png
  assets/advice page.png
  assets/contact page.png
  assets/home page.png
  assets/splash.png
  assets/userstory.png
Labels: waiting-review

#59 update css for buttons,vaccine-title & number in third page
  covid-vaccine-tracker/covid-vaccine-tracker.css
Labels: waiting-review

#60 Modify covid vaccine tracker.js page
  covid-vaccine-tracker/covid-vaccine-tracker.js
Labels: waiting-review
